routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
        return view('auth.login');
});

Auth::routes();

//Route as admin
Route::group(['middleware' => ['web','auth']], function()    
{
    Route::get('/home', 'AdminController@index')->name('home');

    Route::resource('/teacher', 'TeacherController');
    Route::get('/table/teacher', 'TeacherController@dataTable')->name('table.teacher');

    Route::resource('/student', 'StudentController');
    Route::get('/table/student', 'StudentController@dataTable')->name('table.student');

    Route::resource('/class', 'ClassController');
    Route::get('/table/class', 'ClassController@dataTable')->name('table.class');

    Route::get('/class/{id}/detail', 'ClassDetailController@detailClass')->name('detailClass');
    Route::get('/table/{id}/class/detail', 'ClassDetailController@dataTableClassDetail')->name('detailTable');
    Route::get('/class/{id}/register', 'ClassDetailController@studentRegistration')->name('studentRegistration');
    Route::put('/class/{id}/registered', 'ClassDetailController@studentClassUpdate')->name('updateStudentClassId');
    Route::delete('/class/{id}/delete', 'ClassDetailController@studentClassDelete')->name('destroyClassDetail');

    Route::get('/class/convert_pdf/pdf', 'AdminController@pdf')->name('convertPdf');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = "student";
    public $timestamps = false;
    protected $fillable = ['student_name', 'birth_place', 'birth_date', 'gender'];

    public function class(){
    	return $this->belongsTo('App\Class');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use DataTables;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Authentication Checking
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.student.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Student();

        return view('pages.student.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'student_name' => 'required|string|max:100|unique:student,student_name',
            'birth_place' => 'required|string|max:150',
            'birth_date' => 'required',
            'gender' => 'required'
        ]);

        $model = Student::create($request->all());

        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Student::findOrFail($id);

        return view('pages.student.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Student::findOrFail($id);

        return view('pages.student.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'student_name' => 'required|string|max:100|unique:student,student_name',
            'birth_place' => 'required|string|max:150',
            'birth_date' => 'required',
            'gender' => 'required'
        ]);

        $model = Student::findOrFail($id);
        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Student::findOrFail($id);
        $model->delete();
    }

    public function dataTable()
    {
        $model = Student::query();

        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layouts._action_student', [
                    'model' => $model,
                    'url_show' => route('student.show', $model->id),
                    'url_edit' => route('student.edit', $model->id),
                    'url_destroy' => route('student.destroy', $model->id)
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make(true);
    }
}

resources/views/pages/student/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['student.update', $model->id] : 'student.store',
    'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

    <div class="form-group">
        <label for="" class="control-label">Student Name</label>
        <input type="text" name="student_name" value="{{ $model->student_name }}" class="form-control" id="student_name">
    </div>
    <div class="form-group">
        <label for="" class="control-label">Place Of Birth</label>
        <input type="text" name="birth_place" value="{{ $model->birth_place }}" class="form-control" id="birth_place">
    </div>
    <div class="form-group">
        <label for="" class="control-label">Date Of Birth</label>
        <input type="date" name="birth_date" value="{{ $model->birth_date }}" class="form-control" id="birth_date">
    </div>
    <div class="form-group">
        <label for="" class="control-label">Gender</label>
        <select name="gender" class="form-control" id="gender">
            @if ($model->gender == 'female')
                <option value="female" selected="true"> Female </option>
                <option value="male"> Male </option>
            @else
                <option value="male" selected="true"> Male </option>
                <option value="female"> Female </option>
            @endif
        </select>
    </div>

{!! Form::close() !!}

resources/views/pages/student/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Student Data
                <a href="{{ route('student.create') }}" class="btn btn-success pull-right modal-show" style="margin-top: -8px;" title="Create Student"><i class="icon-plus"></i> Add Student</a>
            </h3>
        </div>
        <div class="panel-body">
            <table id="datatable" class="table table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Place Of Birth</th>
                        <th>Date Of Birth</th>
                        <th>Gender</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                      
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Place Of Birth</th>
                        <th>Date Of Birth</th>
                        <th>Gender</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('table.student') }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'student_name', name: 'student_name'},
                {data: 'birth_place', name: 'birth_place'},
                {data: 'birth_date', name: 'birth_date'},
                {data: 'gender', name: 'gender'},
                {data: 'action', name: 'action'}
            ]
        });
    </script>
@endpush

resources/views/pages/student/show.blade.php
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Place Of Birth</th>
        <th>Date Of Birth</th>
        <th>Gender</th>
    </tr>
    <tr>
        <td>{{ $model->id }}</td>
        <td>{{ $model->student_name }}</td>
        <td>{{ $model->birth_place }}</td>
        <td>{{ $model->birth_date }}</td>
        <td>{{ $model->gender }}</td>
    </tr>
</table>