routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
        return view('auth.login');
});

Auth::routes();

//Route as admin
Route::group(['middleware' => ['web','auth']], function()    
{
    Route::get('/home', 'AdminController@index')->name('home');

    Route::resource('/teacher', 'TeacherController');
    Route::get('/table/teacher', 'TeacherController@dataTable')->name('table.teacher');

    Route::resource('/student', 'StudentController');
    Route::get('/table/student', 'StudentController@dataTable')->name('table.student');

    Route::resource('/class', 'ClassController');
    Route::get('/table/class', 'ClassController@dataTable')->name('table.class');

    Route::get('/class/{id}/detail', 'ClassDetailController@detailClass')->name('detailClass');
    Route::get('/table/{id}/class/detail', 'ClassDetailController@dataTableClassDetail')->name('detailTable');
    Route::get('/class/{id}/register', 'ClassDetailController@studentRegistration')->name('studentRegistration');
    Route::put('/class/{id}/registered', 'ClassDetailController@studentClassUpdate')->name('updateStudentClassId');
    Route::delete('/class/{id}/delete', 'ClassDetailController@studentClassDelete')->name('destroyClassDetail');

    Route::get('/class/convert_pdf/pdf', 'AdminController@pdf')->name('convertPdf');
});

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = "teacher";
    public $timestamps = false;
    protected $fillable = ['teacher_name', 'birth_place', 'birth_date'];

    public function class(){
    	return $this->hasMany('App\Classes');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Teacher;
use App\Classes;
use DataTables;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Authentication Checking
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.teacher.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Teacher();

        return view('pages.teacher.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'teacher_name' => 'required|string|max:100|unique:teacher,teacher_name',
            'birth_place' => 'required|string|max:150',
            'birth_date' => 'required'
        ]);

        $model = Teacher::create($request->all());

        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Teacher::findOrFail($id);

        return view('pages.teacher.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Teacher::findOrFail($id);

        return view('pages.teacher.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'teacher_name' => 'required|string|max:100|unique:teacher,teacher_name',
            'birth_place' => 'required|string|max:150',
            'birth_date' => 'required' 
        ]);

        $model = Teacher::findOrFail($id);

        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Teacher::findOrFail($id);

        Classes::where('teacher_id', $id)->update(['teacher_id' => null]);

        $model->delete();
    }

    public function dataTable()
    {
        $model = Teacher::query();
        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layouts._action', [
                    'model' => $model,
                    'url_show' => route('teacher.show', $model->id),
                    'url_edit' => route('teacher.edit', $model->id),
                    'url_destroy' => route('teacher.destroy', $model->id)
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make(true);
    }
}

resources/views/pages/teacher/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['teacher.update', $model->id] : 'teacher.store',
    'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

    <div class="form-group">
        <label for="" class="control-label">Teacher Name</label>
        {!! Form::text('teacher_name', null, ['class' => 'form-control', 'id' => 'teacher_name']) !!}
    </div>
    <div class="form-group">
        <label for="" class="control-label">Place Of Birth</label>
        {!! Form::text('birth_place', null, ['class' => 'form-control', 'id' => 'birth_place']) !!}
    </div>
    <div class="form-group">
        <label for="" class="control-label">Date Of Birth</label>
        {!! Form::date('birth_date', null, ['class' => 'form-control', 'id' => 'birth_date']) !!}
    </div>

{!! Form::close() !!}

resources/views/pages/teacher/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Teacher Data
                <a href="{{ route('teacher.create') }}" class="btn btn-success pull-right modal-show" style="margin-top: -8px;" title="Create Teacher"><i class="icon-plus"></i> Add Teacher</a>
            </h3>
        </div>
        <div class="panel-body">
            <table id="datatable" class="table table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Place Of Birth</th>
                        <th>Date Of Birth</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                      
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Place Of Birth</th>
                        <th>Date Of Birth</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('table.teacher') }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'teacher_name', name: 'teacher_name'},
                {data: 'birth_place', name: 'birth_place'},
                {data: 'birth_date', name: 'birth_date'},
                {data: 'action', name: 'action'}
            ]
        });
    </script>
@endpush

resources/views/pages/teacher/show.blade.php
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Place Of Birth</th>
        <th>Date Of Birth</th>
    </tr>
    <tr>
        <td>{{ $model->id }}</td>
        <td>{{ $model->teacher_name }}</td>
        <td>{{ $model->birth_place }}</td>
        <td>{{ $model->birth_date }}</td>
    </tr>
</table>