routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
        return view('auth.login');
});

Auth::routes();

//Route as admin
Route::group(['middleware' => ['web','auth']], function()    
{
    Route::get('/home', 'AdminController@index')->name('home');

    Route::resource('/teacher', 'TeacherController');
    Route::get('/table/teacher', 'TeacherController@dataTable')->name('table.teacher');

    Route::resource('/student', 'StudentController');
    Route::get('/table/student', 'StudentController@dataTable')->name('table.student');

    Route::resource('/class', 'ClassController');
    Route::get('/table/class', 'ClassController@dataTable')->name('table.class');

    Route::get('/class/{id}/detail', 'ClassDetailController@detailClass')->name('detailClass');
    Route::get('/table/{id}/class/detail', 'ClassDetailController@dataTableClassDetail')->name('detailTable');
    Route::get('/class/{id}/register', 'ClassDetailController@studentRegistration')->name('studentRegistration');
    Route::put('/class/{id}/registered', 'ClassDetailController@studentClassUpdate')->name('updateStudentClassId');
    Route::delete('/class/{id}/delete', 'ClassDetailController@studentClassDelete')->name('destroyClassDetail');

    Route::get('/class/convert_pdf/pdf', 'AdminController@pdf')->name('convertPdf');
});

app/Http/Controllers/ClassController.php
<?php

namespace App\Http\Controllers;

use App\Teacher;
use App\Classes;
use App\Student;
use DataTables;
use Illuminate\Http\Request;

class ClassController extends Controller
{
    /**
     * Authentication Checking
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.class.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Classes();

        $teacher = Teacher::orderBy('id')->get();

        return view('pages.class.form', compact('model'))
            ->with('listTeacher', $teacher);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'class_name' => 'required|string|max:100|unique:class,class_name',
            'teacher_id' => 'required|integer'
        ]);

        $model = Classes::create($request->all());

        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $class = Classes::findOrFail($id);

        return view('pages.class.show', compact('class'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Classes::findOrFail($id);

        $teacher = Teacher::orderBy('id')->get();

        return view('pages.class.form', compact('model'))
            ->with('listTeacher', $teacher);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'class_name' => 'required|string|max:100',
            'teacher_id' => 'required|integer'
        ]);

        $model = Classes::findOrFail($id);

        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) 
    {
        $model = Classes::findOrFail($id);

        Student::where('class_id', $id)->update(['class_id' => null]);

        $model->delete();
    }

    public function dataTable()
    {
        $model = Classes::leftJoin('teacher', 'class.teacher_id', '=', 'teacher.id')
            ->select('class.*', 'teacher.teacher_name')
            ->get();

        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layouts._action_class', [
                    'model' => $model,
                    'url_show' => route('class.show', $model->id),
                    'url_edit' => route('class.edit', $model->id),
                    'url_destroy' => route('class.destroy', $model->id)
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make(true);
    }
}

resources/views/pages/class/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['class.update', $model->id] : 'class.store',
    'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

    <div class="form-group">
        <label for="" class="control-label">Class Name</label>
        <input type="text" name="class_name" value="{{ $model->class_name }}" class="form-control" id="class_name">
    </div>
    <div class="form-group">
        <label for="" class="control-label">Teacher Name</label>
        <select name="teacher_id" class="form-control" id="teacher_id">
            @foreach ($listTeacher as $teacher)
                <option @if ($teacher->id == $model->teacher_id) selected @endif value="{{ $teacher->id }}"> {{ $teacher->teacher_name }} </option>
            @endforeach
        </select>
    </div>

{!! Form::close() !!}

resources/views/pages/class/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Class Data
                <a href="{{ route('class.create') }}" class="btn btn-success pull-right modal-show" title="Create Class"><i class="icon-plus"></i> Add Class
                </a>
                <a href="{{ route('convertPdf') }}" class="btn btn-danger" title="Print Data">Print</a>
            </h3>
        </div>
        <div class="panel-body">
            <table id="datatable" class="table table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Class Name</th>
                        <th>Teacher Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                      
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Class Name</th>
                        <th>Teacher Name</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('table.class') }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'class_name', name: 'class_name'},
                {data: 'teacher_name', name: 'teacher_name'},
                {data: 'action', name: 'action'}
            ]
        });
    </script>
@endpush

resources/views/pages/class/print.blade.php
<<!DOCTYPE html>
<html>
<head>
	<title> Class Management System</title>
</head>
<body>
    <div style='font-size: 9pt; padding-top: -45px'>CMS - Management Service</div>
		<table style='border-bottom: 1px black; padding-left: 170px; padding-top: -20px'>
			<tr>
				<td>
					<div style='font-weight: bold; padding-bottom: 2px; font-size: 12pt; text-align: center'>
						CLASS MANAGEMENT SYSTEM<br>
						LARAVEL TEST
					</div>
					<div style='font-weight: bold; font-size: 10pt; padding-bottom: 5px; text-align: center'>
						LIST CLASS DETAIL
					</div>
					<div style='font-size: 9pt; text-align: center'>
						Address : Indonesia - Manado 12345 Telphone : (00) 12345, Fax : (00) 12345
					</div>
				</td>
			</tr>
		</table>
		<table style='border-bottom: 4px black;  padding-right: 670px'>
		</table>

	    <p style='font-size: 12pt; text-align: center; font-weight: bold'>LIST CLASS DETAIL</p><br>

		<table cellpadding='4' cellspacing='0' style='border-top: 2px; border-bottom: 1px; border-right: 2px; border-left: 2px;'>
			<tr style='background-color: #fcf8e1; '>
				<th style='border-right: 1px; border-bottom: 1px; padding: 5px 0px 5px 0px; font-size: 11pt; text-align: center;'>No.</th>
				<th style='border-right: 1px; border-bottom: 1px; padding: 5px 0px 5px 0px; font-size: 11pt;'>Student Name</th>
				<th style='border-right: 1px; border-bottom: 1px; padding: 5px 0px 5px 0px; font-size: 11pt;'>Teacher Name</th>
				<th style='border-right: 1px; border-bottom: 1px; padding: 5px 0px 5px 0px; font-size: 11pt; text-align: center;'>Class Name</th>
			</tr>
			<?php $i=1; ?>
	        @foreach ($get_data as $get) 
			<tr align="top">
				<td style="border-right: 1px; border-bottom: 1px; width: 25mm; padding: 5px 0px 5px 5px; font-size: 10pt; text-align: center">{{$i}}</td>
				<td style="border-right: 1px; border-bottom: 1px; width: 60mm; padding: 5px 0px 5px 5px; font-size: 10pt;">{{ $get->student_name }}</td>
				<td style="border-right: 1px; border-bottom: 1px; width: 60mm; padding: 5px 0px 5px 5px; font-size: 10pt;">{{ $get->teacher_name }}</td>
				<td style="border-right: 1px; border-bottom: 1px; width: 45mm; padding: 5px 0px 5px 5px; font-size: 10pt; text-align: center">{{ $get->class_name }}</td>
			</tr>
			<?php $i++; ?>
			@endforeach
	    </table>
</body>
</html>       
		

resources/views/pages/class/show.blade.php
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Class Name</th>
        <th>Teacher Name</th>
    </tr>
    <tr>
        <td>{{ $class->id }}</td>
        <td>{{ $class->class_name }}</td>
        <td>{{ $class->teacher->teacher_name }}</td>
    </tr>
</table>